// 389. Find the Difference


// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.


Input: s = "abcd", 
t = "abcde"


var findTheDifference = function(s, t) {
    let sortedS=s.split('').sort().join('')
    let sortedT=t.split('').sort().join('')

  for(let i=0;i<sortedS.length;i++){
        if(sortedS[i]!==sortedT[i]){
            return sortedT[i]
            
        }
    }
    return sortedT[sortedT.length-1]
    
};

console.log(findTheDifference(s,t))  //Output-6